#!/usr/bin/env python3
"""Generate ready-to-run SQL for the Eurostat Comext schemas (eu_comext_*).

Comext series IDs must be constructed exactly (pattern scans time out; string
ranges return wrong rows — see references/data/sql-guide.md). This emits the
correct exact-ID SQL mechanically: the cn6_total series for all-goods totals,
lookup-table joins for product breakdowns, and UNION ALL across any set of
the 27 reporter schemas. Run the output with the run_sql tool using the
schema printed in the header comment.

ID grammar it encodes:
  eu_comext_{M|X}_{reporter}_{partner}_{te|ti}_p1_cn8_{code}_{eur|kg|su}
  - reporter/partner: lowercase ISO2. Trade token: `ti` when the partner is
    an EU member (intra-EU), else `te` (extra-EU). Chosen automatically.
  - metric: _eur value, _kg weight, _su supplementary quantity — never summed
    together. All-goods totals use the exact `cn6_total` product token.

Examples:
  python3 scripts/comext_sql.py total --reporters all --partner cn --flow imports \
      --start 2025-01 --end 2025-12
  python3 scripts/comext_sql.py total --reporters de,fr,nl --partner us --flow exports \
      --start 2024-01 --end 2025-12 --monthly
  python3 scripts/comext_sql.py products --reporters all --partner cn --flow imports \
      --start 2025-01 --end 2025-12 --group-by 4 --top 25
  python3 scripts/comext_sql.py trend --reporters de --partner cn --flow imports \
      --hs 8507 --start 2020-01 --end 2025-12

Label the HS codes a products/trend query returns with scripts/hs_codes.py.
"""
from __future__ import annotations

import argparse
import json
import sys

EU_MEMBERS = [
    "at", "be", "bg", "hr", "cy", "cz", "dk", "ee", "fi", "fr", "de", "gr",
    "hu", "ie", "it", "lv", "lt", "lu", "mt", "nl", "pl", "pt", "ro", "sk",
    "si", "es", "se",
]

METRICS = {"value": "eur", "weight": "kg", "supplementary": "su"}
METRIC_UNITS = {"value": "EUR", "weight": "kg", "supplementary": "supplementary units"}


def fail(message: str, code: int = 1) -> None:
    print(json.dumps({"error": message}), file=sys.stderr)
    sys.exit(code)


def parse_month(text: str, name: str) -> tuple[int, int]:
    parts = text.split("-")
    if len(parts) != 2 or not (parts[0].isdigit() and parts[1].isdigit()):
        fail(f"--{name} must be YYYY-MM, got '{text}'")
    year, month = int(parts[0]), int(parts[1])
    if not 1 <= month <= 12:
        fail(f"--{name} month out of range in '{text}'")
    return year, month


def date_bounds(start: str, end: str) -> tuple[str, str]:
    """Inclusive month range -> [first day of start, first day after end)."""
    sy, sm = parse_month(start, "start")
    ey, em = parse_month(end, "end")
    if (sy, sm) > (ey, em):
        fail(f"--start {start} is after --end {end}")
    ny, nm = (ey + 1, 1) if em == 12 else (ey, em + 1)
    return f"{sy:04d}-{sm:02d}-01", f"{ny:04d}-{nm:02d}-01"


def resolve_reporters(text: str) -> list[str]:
    if text.strip().lower() == "all":
        return list(EU_MEMBERS)
    reporters = [r.strip().lower() for r in text.split(",") if r.strip()]
    bad = [r for r in reporters if r not in EU_MEMBERS]
    if bad:
        fail(
            f"unknown reporter(s) {bad}: reporters are the 27 EU members as "
            f"lowercase ISO2 ({', '.join(EU_MEMBERS)}) or 'all'"
        )
    return reporters


def resolve_partner(text: str) -> str:
    partner = text.strip().lower()
    if not (len(partner) == 2 and partner.isalpha()):
        fail(
            f"--partner must be a lowercase ISO2 country code (e.g. cn, us, gb, in), got '{text}'"
        )
    return partner


def trade_token(partner: str) -> str:
    return "ti" if partner in EU_MEMBERS else "te"


def flow_code(flow: str) -> str:
    return {"imports": "M", "exports": "X", "m": "M", "x": "X"}[flow.lower()]


def total_series_id(flow: str, reporter: str, partner: str, suffix: str) -> str:
    return f"eu_comext_{flow}_{reporter}_{partner}_{trade_token(partner)}_p1_cn6_total_{suffix}"


def product_id_expr(flow: str, reporter: str, partner: str, suffix: str) -> str:
    prefix = f"eu_comext_{flow}_{reporter}_{partner}_{trade_token(partner)}_p1_cn8_"
    return f"'{prefix}' || lower(p.product_code) || '_{suffix}'"


def header(reporters: list[str], args: argparse.Namespace, extra: str = "") -> str:
    lines = [
        f"-- generated by comext_sql.py {args.command}: "
        f"{args.flow} vs partner '{args.partner}', {args.start}..{args.end}, metric={args.metric}",
        f'-- run with the run_sql tool, schema="eu_comext_{reporters[0]}"',
    ]
    if extra:
        lines.append(f"-- {extra}")
    return "\n".join(lines)


def sql_total(args: argparse.Namespace) -> str:
    reporters = resolve_reporters(args.reporters)
    partner = resolve_partner(args.partner)
    flow = flow_code(args.flow)
    suffix = METRICS[args.metric]
    lo, hi = date_bounds(args.start, args.end)

    # Each reporter schema holds only its own series in data_points, so every
    # reporter needs its own qualified branch — a flat IN list against one
    # schema's table would silently drop the other 26.
    branches = []
    for r in reporters:
        table = "data_points" if len(reporters) == 1 else f"eu_comext_{r}.data_points"
        branches.append(
            f"  SELECT '{r}' AS reporter, time AS t, value AS v\n"
            f"  FROM {table}\n"
            f"  WHERE series_id = '{total_series_id(flow, r, partner, suffix)}'\n"
            f"    AND time >= DATE '{lo}' AND time < DATE '{hi}'"
        )
    union = "\nUNION ALL\n".join(branches)
    if args.monthly:
        select, group = f"t::date AS month, SUM(v) AS total_{suffix}", "GROUP BY t\nORDER BY t"
    else:
        select, group = f"reporter, SUM(v) AS total_{suffix}", "GROUP BY reporter\nORDER BY 2 DESC"
    body = f"SELECT {select}\nFROM (\n{union}\n) u\n{group};"
    note = f"all-goods total via the exact cn6_total series; values in {METRIC_UNITS[args.metric]}"
    return header(reporters, args, note) + "\n" + body


def product_branches(
    reporters: list[str],
    partner: str,
    flow: str,
    suffix: str,
    lo: str,
    hi: str,
    inner_select: str,
    where_extra: str,
) -> str:
    branches = []
    for r in reporters:
        table = "data_points" if len(reporters) == 1 else f"eu_comext_{r}.data_points"
        branches.append(
            f"  SELECT {inner_select.format(reporter=r)}\n"
            f"  FROM eu_comext_lookup.product_codes p\n"
            f"  JOIN {table} dp\n"
            f"    ON dp.series_id = {product_id_expr(flow, r, partner, suffix)}\n"
            f"  WHERE p.is_numeric_cn8\n"
            f"    AND p.last_observed >= DATE '{lo}' AND p.first_observed < DATE '{hi}'\n"
            f"    AND dp.time >= DATE '{lo}' AND dp.time < DATE '{hi}'{where_extra}"
        )
    return "\nUNION ALL\n".join(branches)


def sql_products(args: argparse.Namespace) -> str:
    reporters = resolve_reporters(args.reporters)
    partner = resolve_partner(args.partner)
    flow = flow_code(args.flow)
    suffix = METRICS[args.metric]
    lo, hi = date_bounds(args.start, args.end)

    group_col = {
        "2": "p.hs2_code",
        "4": "p.hs4_code",
        "6": "p.hs6_code",
        "cn8": "lower(p.product_code)",
    }[args.group_by]
    inner = f"{group_col} AS code, dp.value AS v"
    union = product_branches(reporters, partner, flow, suffix, lo, hi, inner, "")
    body = (
        f"SELECT code, SUM(v) AS total_{suffix}\n"
        f"FROM (\n{union}\n) t\n"
        f"GROUP BY code\n"
        f"ORDER BY 2 DESC\n"
        f"LIMIT {args.top};"
    )
    label_hint = (
        "name the codes locally: python3 scripts/hs_codes.py <codes>"
        if args.group_by in ("2", "4", "6")
        else "CN8 names live in eu_comext_lookup.product_codes.product_name"
    )
    note = f"top products by HS{args.group_by}; values in {METRIC_UNITS[args.metric]}; {label_hint}"
    return header(reporters, args, note) + "\n" + body


def sql_trend(args: argparse.Namespace) -> str:
    reporters = resolve_reporters(args.reporters)
    partner = resolve_partner(args.partner)
    flow = flow_code(args.flow)
    suffix = METRICS[args.metric]
    lo, hi = date_bounds(args.start, args.end)

    code = args.hs.strip().lower()
    if len(code) not in (2, 4, 6, 8) or not code.isalnum():
        fail(f"--hs must be a 2/4/6-digit HS code or an 8-digit CN8 code, got '{args.hs}'")
    if len(code) == 8:
        where_extra = f"\n    AND lower(p.product_code) = '{code}'"
    else:
        col = {2: "p.hs2_code", 4: "p.hs4_code", 6: "p.hs6_code"}[len(code)]
        where_extra = f"\n    AND {col} = '{code}'"

    inner = "dp.time AS t, dp.value AS v"
    union = product_branches(reporters, partner, flow, suffix, lo, hi, inner, where_extra)
    body = (
        f"SELECT t::date AS month, SUM(v) AS total_{suffix}\n"
        f"FROM (\n{union}\n) u\n"
        f"GROUP BY t\n"
        f"ORDER BY t;"
    )
    note = f"monthly trend for HS {code}; values in {METRIC_UNITS[args.metric]}"
    return header(reporters, args, note) + "\n" + body


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    sub = parser.add_subparsers(dest="command", required=True)

    def add_common(p: argparse.ArgumentParser) -> None:
        p.add_argument("--reporters", required=True, help="comma-separated lowercase ISO2 EU members, or 'all'")
        p.add_argument("--partner", required=True, help="partner country, lowercase ISO2 (cn, us, gb, ...)")
        p.add_argument("--flow", required=True, choices=["imports", "exports"])
        p.add_argument("--start", required=True, help="first month, YYYY-MM (inclusive)")
        p.add_argument("--end", required=True, help="last month, YYYY-MM (inclusive)")
        p.add_argument("--metric", default="value", choices=sorted(METRICS), help="default: value (EUR)")

    p_total = sub.add_parser("total", help="all-goods totals via the exact cn6_total series")
    add_common(p_total)
    p_total.add_argument("--monthly", action="store_true", help="one row per month instead of one per reporter")

    p_products = sub.add_parser("products", help="top products via the lookup-table join")
    add_common(p_products)
    p_products.add_argument("--group-by", default="4", choices=["2", "4", "6", "cn8"], help="HS grouping level (default 4)")
    p_products.add_argument("--top", type=int, default=25, help="rows to return (default 25, tool cap 50)")

    p_trend = sub.add_parser("trend", help="monthly trend for one HS group or CN8 line")
    add_common(p_trend)
    p_trend.add_argument("--hs", required=True, help="2/4/6-digit HS code or 8-digit CN8 code")

    args = parser.parse_args()
    print({"total": sql_total, "products": sql_products, "trend": sql_trend}[args.command](args))


if __name__ == "__main__":
    main()
